### ISSUE TITLE
Satpy-Entwickler anschreiben wegen nc-reader-Update

### ISSUE THREAD

**Issue by sebiegli** [python-kurs/sommersemester_2019#4]
das sollte möglichst im master sein, damit wir es vor der Satpy-Session am 12.06.2019 überall installieren können

**Comment by BENR0** [comment]
probier mal den neuen master aus. es gab ein paar fixes. cf writer sollte damit auch funktionieren. hrv funktioniert auch wohl aber nur wenn man den einzeln lädt...

update: HRV lässt sich laden, anschauen und schreiben aber extent/georef ist falsch...
