### ISSUE TITLE
SatPy Writer reparieren (s. S01E06 Ende)

### ISSUE THREAD

**Issue by sebiegli** [python-kurs/sommersemester_2019#6]
Das Beispiel von der Satpy-Doku klappt nicht: https://satpy.readthedocs.io/en/latest/writers.html

ValueError: Invalid format specifier

**Comment by BENR0** [comment]
funktioniert jetzt mit den fixes die für den nc reader gemerged werden bei mir auch. die tiffs werden alle auf den wertebereich von 0-255 skaliert. wenn man das verhindern möchte und die original values haben möchte:

`msg.save_datasets(filename="satpy_cf_writer_test_{name}.tiff", dtype=np.float32, enhance=False)`
