### ISSUE TITLE
Jupyter-Book auf github pages updaten 

### ISSUE THREAD

**Issue by sebiegli** [python-kurs/sommersemester_2019#7]
(damit # HIDECELL auch online funktioniert)

**Comment by BENR0** [comment]
Ok also alles sehr verwirrend:

1. nachdem die fixes aus meinem PR in den Master gemerged wurden hatte ich das travis config schon geupdated dahingehend das nicht mehr von meinem Fork installiert wird. => ich bin verwirrt warum # HIDECELL nicht funktiniert (bei mir gehts lokal auch...)
2. das tag removecell gilt nur für code cells nicht für markdown cells. deshalb geht das nicht (steht so nicht in der doku aber hab die info in einem issue gefunden :-/ )
3. meine vermutung ist gerade das es evtl. mit den anderen tags zu tun hat. versuche das mal zu verifizieren...

**Comment by BENR0** [comment]
ok falsch gedacht. keine ahnung was das problem ist. ich mache mal nen issue bei jupyter book auf.

**Comment by sebiegli** [comment]
ok, dann lass ich das issue so lange nochmal offen

**Comment by BENR0** [comment]
Hab den Fehler gefunden. Für die task, info und solution tags musste ich das jekyll template anpassen damit unser custom css eingefügt wird. Daher konnte der Fix vom jupyter-book master auch nicht funktionieren weil unser template immer das von jupyter-book überschrieben hat.

Jetzt sollte es funktionieren mit "remove_cell" markdown cells raus zu nehmen. Habe das auch in Unit 6 schon hinzugefügt.

**Comment by sebiegli** [comment]
supi, dann schließe ich das issue hier
